### ISSUE TITLE
Migrate artifacts to maven central

### ISSUE THREAD

**Issue by halu5071** [halu5071/edwards#38]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by iiordanov** [comment]
Hi @halu5071, people are reporting that they are unable to build my project anymore. For instance, see https://github.com/iiordanov/remote-desktop-clients/issues/333. Are you in a position to fix this issue? Thanks!!

**Comment by halu5071** [comment]
@iiordanov 
Thank you for your reporting!!
I'm now working to publish my artifact on Maven Central.
I will publish new release as 0.8.0, after my work for this repo.

Here's my ticket for SONATYPE.
https://issues.sonatype.org/browse/OSSRH-77549

Thanks!

**Comment by halu5071** [comment]
@iiordanov 
New release 0.8.1 was published on Maven Central.
https://search.maven.org/artifact/io.moatwel.crypto/eddsa/0.8.1/jar

**Comment by halu5071** [comment]
Migration to maven central was completed. I close this issue.

**Comment by mjuned47** [comment]
@halu5071 can you upload 0.7.0-beta version? Because new version is not compiling with app

**Comment by halu5071** [comment]
@mjuned47 
I published 0.7.0-beta on maven central.
https://search.maven.org/artifact/io.moatwel.crypto/eddsa/0.7.0-beta/jar

**Comment by iiordanov** [comment]
Thank you kindly @halu5071!
