### ISSUE TITLE
Edwards-curve Digital Signature Algorithm (EdDSA)

### ISSUE THREAD

**Issue by TransmachSystems** [halu5071/edwards#48]
why is taking time to verified

public boolean validateSignature(String decodedPayload, String signature) {
        try {
            Edwards edwards = new Edwards(new Ed25519SchemeProvider(HashAlgorithm.SHA_512));
            PublicKey publicKey = new PublicKey(Base64.getDecoder().decode("your public key));
            byte[] sig = hexStringToByteArray(signature);
            byte[] r = ByteUtils.split(sig, 32)[0];
            byte[] s = ByteUtils.split(sig, 32)[1];
            Sig signature1 = new Sig(r, s);
            Log.e(TAG, "signature Start:");
            boolean isVerified = edwards.verify(publicKey, decodedPayload.getBytes(StandardCharsets.UTF_8), signature1);
            Log.e(TAG, "signature End:");
            return isVerified;
        } catch (Exception e) {
            return false;
        }
    }

**Comment by halu5071** [comment]
Could you provide a minimum sample project which can reproduce your issue?

2023年4月21日(金) 19:02 TransmachSystems ***@***.***>:

**Comment by halu5071** [comment]
I will close this issue due to inactive for over 60 days.
